### ISSUE TITLE
terminator.selfies no where be found

### ISSUE THREAD

**Issue by Chippop** [IBM/regression-transformer#19]
Hello,
I looked through all your code and was unable to find the file 'selfies.py'. This is referenced by 
https://github.com/codeaudit/gt4sd-core/blob/a15a1cf90c9bc20e29cf2d73f25441fe25d2640c/src/gt4sd/training_pipelines/regression_transformer/utils.py (line 9)

**Comment by drugilsberg** [comment]
Hey @Chippop in gt4sd we install a specific branch called `gt4sd` of regression transformers that has that file https://github.com/IBM/regression-transformer/tree/gt4sd/terminator.

Here you can see the  requirements entry we use to install it: https://github.com/GT4SD/gt4sd-core/blob/ea9c299cea6ea6c63696b4e9ee49ceb16fb58507/vcs_requirements.txt#L12.
