### ISSUE TITLE
Missing BeamSearch class

### ISSUE THREAD

**Issue by mpaszkow** [IBM/regression-transformer#4]
The BeamSearch class is not implemented in the [terminator/search.py](https://github.com/IBM/regression-transformer/blob/dfc5a48fbc30022a15c1ba542ef15fb61651c1e7/terminator/search.py) module, but it's imported in the [terminator/evaluator.py](https://github.com/IBM/regression-transformer/blob/dfc5a48fbc30022a15c1ba542ef15fb61651c1e7/terminator/evaluator.py#L20) file and used by the Evaluator class. Any attempt to import the Evaluator (e.g. in [terminator/trainer.py](https://github.com/IBM/regression-transformer/blob/dfc5a48fbc30022a15c1ba542ef15fb61651c1e7/terminator/trainer.py#L1176)) leads to an error:

`ImportError: cannot import name 'BeamSearch' from 'terminator.search' (search.py)`

**Comment by jannisborn** [comment]
Hi @mpaszkow,
Thanks for the interest in our work. You're totally right, my bad. I will create a PR to fix this!
