### ISSUE TITLE
Problem with example

### ISSUE THREAD

**Issue by pjuangph** [IBM/regression-transformer#6]
I ran this code `python scripts/generate_example_data.py examples/example.smi examples/qed_property_example.txt` 

And it produced this error

> [15:35:57] Explicit valence for atom # 1 N, 6, is greater than permitted
> Problem processing SMILES=O=[N](=O)=

Can the authors take a look? Thanks.

**Comment by jannisborn** [comment]
Hi @pjuangph,
thanks for reporting! This was simply caused by an invalid SMILES in the test dataset. I just removed that molecule in 38b3437, the example runs fine now.
Sorry for the inconvenience and let us know if you observe anything else.
