### ISSUE TITLE
PropertyTokenizerSquare no where to be found

### ISSUE THREAD

**Issue by pjuangph** [IBM/regression-transformer#8]
I looked through all your code and was unable to find the class `PropertyTokenizerSquare`. This is referenced by `run_lm_nlp.py`

**Comment by jannisborn** [comment]
Hi @pjuangph,
Thanks for your interest. This class is available in `terminator.tokenization` from the `main` branch, see [here](https://github.com/IBM/regression-transformer/blob/04cef2723ff9e3b7be2175ca97b108e0003f3b63/terminator/tokenization.py#L73).

Hope this helps! Let us know if you need further advice
